import type { DeckDefinition, RulesetManifest } from '../../core/types';

const voyagersDeck: DeckDefinition = {
  id: 'voyage-deck',
  name: 'Voyage Deck',
  description: 'A small scaffold deck that demonstrates how a new ruleset can bring its own cards.',
  cardBack: 'voyagers-card-back',
  defaultSize: 'poker',
  cards: [
    {
      id: 'chart-the-current',
      title: 'Chart the Current',
      type: 'event',
      subtitle: 'Route',
      rarity: 'common',
      icon: 'CC',
      feature: 'Gain 1 course progress.',
      rulesText: 'Add 1 course progress as the crew finds a favorable lane.',
      artDirection: 'A weathered map table, brass compass, green wax marks, and lantern light.',
      accent: '#9bd486',
      effect: { progress: 1 },
    },
    {
      id: 'reef-shadow',
      title: 'Reef Shadow',
      type: 'hazard',
      subtitle: 'Hazard',
      rarity: 'common',
      icon: 'RS',
      feature: 'Raise peril by 1 unless a lookout token is active.',
      rulesText: 'Gain 1 peril. A ward-style token can cancel this card.',
      artDirection: 'Dark reef silhouettes under teal water and a moonlit hull.',
      accent: '#6fc3b2',
      effect: { danger: 1 },
    },
    {
      id: 'steady-lookout',
      title: 'Steady Lookout',
      type: 'boon',
      subtitle: 'Boon',
      rarity: 'rare',
      icon: 'SL',
      feature: 'Prepare a lookout token and reduce peril by 1.',
      rulesText: 'Reduce peril by 1 and activate a lookout token.',
      artDirection: 'A cloak on the mast rail, green dawn, and rain-bright rope.',
      accent: '#b9d889',
      effect: { dangerRelief: 1, ward: true },
    },
    {
      id: 'harbor-sprint',
      title: 'Harbor Sprint',
      type: 'ritual',
      subtitle: 'Final Push',
      rarity: 'mythic',
      icon: 'HS',
      feature: 'Roll a d12 to close distance before the storm catches you.',
      rulesText: 'Roll a d12. On 8+, gain 3 course progress. Otherwise gain 1 peril.',
      artDirection: 'A small ship racing between green signal fires and silver rain.',
      accent: '#e0d88b',
      effect: { rollTarget: 8, rollProgress: 3, rollDanger: 1 },
    },
  ],
};

export const exampleVoyagersManifest: RulesetManifest = {
  id: 'example-voyagers',
  name: 'Example Voyagers',
  tagline: 'A minimal ruleset scaffold for adding your own game.',
  summary:
    'This intentionally small plugin shows the pieces a custom ruleset owns: terminology, dice, deck content, zones, counters, assets, modules, and theme values.',
  objective: 'Reach safe harbor before peril overwhelms the voyage.',
  terminology: {
    progress: 'Course',
    danger: 'Peril',
    deck: 'Voyage Deck',
    discard: 'Wake',
    table: 'Sea Chart',
    ward: 'Lookout',
  },
  dice: [
    {
      id: 'voyage-d12',
      label: 'Voyage d12',
      notation: '1d12',
      faces: 12,
      defaultMode: 'neutral',
      modes: ['advantage', 'neutral', 'risk'],
      successTarget: 8,
      criticalTarget: 12,
    },
  ],
  decks: [voyagersDeck],
  zones: [
    { id: 'deck', label: 'Voyage Deck', role: 'Draw stack', x: 0.08, y: 0.55, width: 0.16, height: 0.28 },
    { id: 'table', label: 'Sea Chart', role: 'Active route cards', x: 0.3, y: 0.22, width: 0.4, height: 0.54 },
    { id: 'discard', label: 'Wake', role: 'Resolved cards', x: 0.75, y: 0.55, width: 0.17, height: 0.28 },
    { id: 'player', label: 'Crew Rail', role: 'Future character sheets', x: 0.14, y: 0.82, width: 0.72, height: 0.1 },
  ],
  counters: [
    { id: 'progress', label: 'Course', max: 7, tone: 'warm' },
    { id: 'danger', label: 'Peril', max: 5, tone: 'threat' },
    { id: 'ward', label: 'Lookout', max: 1, tone: 'cool' },
  ],
  assets: {
    iconSet: 'nautical-crest',
    cardBacks: {
      'voyagers-card-back': '/assets/card-backs/voyagers.png',
    },
    tokenIcons: {
      lookout: '/assets/tokens/lookout.png',
      peril: '/assets/tokens/peril.png',
      course: '/assets/tokens/course.png',
    },
    textureHints: ['green felt', 'weathered map paper', 'brass compass lines'],
  },
  visualTheme: {
    themeId: 'verdant',
    accent: '#9bd486',
    tableFelt: '#102018',
    cardStock: '#eef1d6',
    glow: '#9bd486',
  },
  modules: [
    {
      id: 'sheet-scaffold',
      label: 'Sheet Scaffold',
      status: 'scaffold',
      description: 'A placeholder for voyage roles, supplies, and conditions.',
    },
    {
      id: 'route-generator',
      label: 'Route Generator',
      status: 'planned',
      description: 'Future random table module for islands, hazards, and rumors.',
    },
  ],
  actions: [
    {
      id: 'draw-route',
      label: 'Draw Route',
      detail: 'Reveal a voyage card and update the sea chart.',
      kind: 'draw',
    },
    {
      id: 'roll-course',
      label: 'Course Roll',
      detail: 'Roll the active voyage die without drawing.',
      kind: 'roll',
    },
    {
      id: 'cycle-dice',
      label: 'Dice Mode',
      detail: 'Rotate the dice handling mode.',
      kind: 'cycle-dice',
    },
    {
      id: 'reset-voyage',
      label: 'Reset Voyage',
      detail: 'Shuffle the voyage deck and clear counters.',
      kind: 'reset',
    },
  ],
};
