import type { CardSpec, DeckCardDefinition, DeckDefinition, DemoRules } from '../core/types';

export const cardSpecs: CardSpec[] = [
  {
    sizeId: 'poker',
    widthPx: 750,
    heightPx: 1050,
    widthMm: 63,
    heightMm: 88,
    purpose: 'Standard playing-card format for primary draw decks, table handling, sleeves, and print-friendly exports.',
  },
  {
    sizeId: 'mini-board',
    widthPx: 360,
    heightPx: 220,
    widthMm: 90,
    heightMm: 55,
    purpose: 'Encounter guides, turn aids, boss scenes, and rules references beside the table.',
  },
  {
    sizeId: 'token',
    widthPx: 96,
    heightPx: 96,
    widthMm: 24,
    heightMm: 24,
    purpose: 'Markers for danger, wards, focus, exhaustion, and custom ruleset states.',
  },
];

export const emberveilCards: DeckCardDefinition[] = [
  {
    id: 'glass-sky',
    title: 'Glass Sky',
    type: 'omen',
    subtitle: 'Omen',
    rarity: 'common',
    icon: 'OS',
    feature: 'Gain 1 seal progress through careful foresight.',
    rulesText: 'Reveal the next sign and gain 1 seal progress.',
    artDirection: 'Cracked celestial mirror, pale moons, and silver dust over a storm horizon.',
    accent: '#87d7f8',
    effect: { progress: 1 },
  },
  {
    id: 'choir-of-cinders',
    title: 'Choir of Cinders',
    type: 'omen',
    subtitle: 'Omen',
    rarity: 'rare',
    icon: 'CC',
    feature: 'Rewards prepared tables with extra seal progress.',
    rulesText: 'Gain 2 seal progress if a boon is in the discard. Otherwise gain 1.',
    artDirection: 'Choir robes dissolving into sparks above an altar of ash and gold.',
    accent: '#ff8f61',
    effect: { progress: 1, preparedProgress: 1 },
  },
  {
    id: 'eclipsed-belfry',
    title: 'Eclipsed Belfry',
    type: 'omen',
    subtitle: 'Omen',
    rarity: 'rare',
    icon: 'EB',
    feature: 'Pushes a stable table toward a decisive turn.',
    rulesText: 'Gain 1 seal progress. If danger is 1 or less, gain 1 additional progress.',
    artDirection: 'A bell tower in eclipse, wrapped in ash haze and distant gold fire.',
    accent: '#d8b0ff',
    effect: { progress: 1, stableProgress: 1 },
  },
  {
    id: 'lantern-oath',
    title: 'Lantern Oath',
    type: 'boon',
    subtitle: 'Boon',
    rarity: 'common',
    icon: 'LO',
    feature: 'Reduces danger by 1 and steadies the table.',
    rulesText: 'Reduce danger by 1. This boon counts as preparation for future cards.',
    artDirection: 'Warm brass lantern light, parchment dust, and a hand-bound vow ribbon.',
    accent: '#f0c86a',
    effect: { dangerRelief: 1 },
  },
  {
    id: 'mercy-salt',
    title: 'Mercy Salt',
    type: 'boon',
    subtitle: 'Boon',
    rarity: 'rare',
    icon: 'MS',
    feature: 'Cancels the next hazard and protects the next pressure spike.',
    rulesText: 'Activate a ward. The next hazard is ignored, then the ward is spent.',
    artDirection: 'White salt circles, careful fingertips, and pale blue protective sparks.',
    accent: '#d8f3ff',
    effect: { ward: true },
  },
  {
    id: 'crown-of-wax',
    title: 'Crown of Wax',
    type: 'boon',
    subtitle: 'Boon',
    rarity: 'mythic',
    icon: 'CW',
    feature: 'A safeguard that can swing a losing encounter.',
    rulesText: 'Reduce danger by 2 and activate a ward against the next hazard.',
    artDirection: 'Molten candle crown with jewel-like drips glowing over black silk.',
    accent: '#ffd27c',
    effect: { dangerRelief: 2, ward: true },
  },
  {
    id: 'grave-wind',
    title: 'Grave Wind',
    type: 'hazard',
    subtitle: 'Hazard',
    rarity: 'common',
    icon: 'GW',
    feature: 'A baseline pressure spike that raises danger.',
    rulesText: 'Gain 1 danger unless a ward prevents it.',
    artDirection: 'Obsidian fog crossing old graves, with a cyan edge glow in the wind.',
    accent: '#7fb8c8',
    effect: { danger: 1 },
  },
  {
    id: 'veil-crack',
    title: 'Veil Crack',
    type: 'hazard',
    subtitle: 'Hazard',
    rarity: 'rare',
    icon: 'VC',
    feature: 'Punishes unstable tables with extra danger.',
    rulesText: 'Gain 2 danger if danger is already 2 or higher. Otherwise gain 1.',
    artDirection: 'A jagged rift of violet-black ash opening across a chapel floor.',
    accent: '#ba7cff',
    effect: { danger: 1, rollDanger: 1 },
  },
  {
    id: 'midnight-abbot',
    title: 'Midnight Abbot',
    type: 'hazard',
    subtitle: 'Hazard',
    rarity: 'mythic',
    icon: 'MA',
    feature: 'A showcase hazard that can nearly break the table on its own.',
    rulesText: 'Gain 2 danger unless a ward blunts the effect.',
    artDirection: 'A towering abbot silhouette in velvet black with a halo of extinguished gold.',
    accent: '#c07cff',
    effect: { danger: 2 },
  },
  {
    id: 'ashen-rite',
    title: 'Ashen Rite',
    type: 'ritual',
    subtitle: 'Major Ritual',
    rarity: 'common',
    icon: 'AR',
    feature: 'Reliable scoring if you land the cast.',
    rulesText: 'Roll a d20. On 11+, gain 2 progress. Otherwise gain 1 progress and 1 danger.',
    artDirection: 'Soot-black vellum, ember filigree, and a bright molten sigil in the center.',
    accent: '#d9914b',
    effect: { rollTarget: 11, rollProgress: 2, progress: 1, rollDanger: 1 },
  },
  {
    id: 'saintless-hour',
    title: 'Saintless Hour',
    type: 'ritual',
    subtitle: 'Major Ritual',
    rarity: 'rare',
    icon: 'SH',
    feature: 'A strong closer that can finish the seal in one move.',
    rulesText: 'Roll a d20. On 13+, gain 3 progress. On failure, gain 1 danger.',
    artDirection: 'Dark nave architecture pierced by one immaculate beam of dawn.',
    accent: '#ffe5aa',
    effect: { rollTarget: 13, rollProgress: 3, rollDanger: 1 },
  },
  {
    id: 'cathedral-engine',
    title: 'Cathedral Engine',
    type: 'ritual',
    subtitle: 'Grand Ritual',
    rarity: 'mythic',
    icon: 'CE',
    feature: 'The centerpiece ritual for late-game climaxes.',
    rulesText: 'Roll a d20. On 14+, gain 4 progress. Otherwise gain 2 danger.',
    artDirection: 'A colossal ritual machine of brass, relic ivory, and glowing stained light.',
    accent: '#f7e1a3',
    effect: { rollTarget: 14, rollProgress: 4, rollDanger: 2 },
  },
];

export const emberveilDeck: DeckDefinition = {
  id: 'omen-deck',
  name: 'Omen Deck',
  description: 'A compact pressure deck for the Emberveil example ruleset.',
  cardBack: 'emberveil-card-back',
  defaultSize: 'poker',
  cards: emberveilCards,
};

export const demoDeck = emberveilCards;

export const demoRules: DemoRules = {
  winCondition: 'Reach 7 seal progress before danger reaches 5.',
  lossCondition: 'If danger reaches 5 or the deck empties before the seal is completed, the breach wins.',
  turnStructure: [
    'Draw 1 card from the active ruleset deck.',
    'Resolve the card effect through the shared card engine.',
    'Roll only if the card calls for a dice profile check.',
    'Check counters, zones, and the session log before continuing.',
  ],
  cardSpecs,
  cardTypeGuide: [
    {
      type: 'omen',
      role: 'Tempo and information',
      function: 'Smooth the encounter pace and create ritual momentum.',
      quantity: '3 cards in the scaffold deck',
    },
    {
      type: 'hazard',
      role: 'Threat escalation',
      function: 'Raise danger, punish greed, and keep the table physically tense.',
      quantity: '3 cards in the scaffold deck',
    },
    {
      type: 'boon',
      role: 'Control tools',
      function: 'Lower danger, establish wards, and set up larger ritual turns.',
      quantity: '3 cards in the scaffold deck',
    },
    {
      type: 'ritual',
      role: 'Primary scoring',
      function: 'Turn preparation and nerve into seal progress.',
      quantity: '3 cards in the scaffold deck',
    },
  ],
  sections: [
    {
      title: 'Core Loop',
      body: 'The demo run is a static-friendly tabletop loop: draw a card, resolve its effect, update counters, and keep the full experience inside client state.',
    },
    {
      title: 'Dice Model',
      body: 'Rulesets define dice profiles and permitted modes. The shared dice engine returns transparent roll metadata that UI panels, logs, and future plugins can reuse.',
    },
    {
      title: 'Card Feel',
      body: 'Cards are plain TypeScript definitions today, but every card has IDs, art direction, accent color, rules text, and effect hooks ready for asset-backed rendering.',
    },
  ],
};
